service: hpefunctions
frameworkVersion: "3"

provider:
  name: aws
  architecture: x86_64
  region: ap-northeast-1
  stage: prod
  runtime: python3.9
  iam:
    role: arn:aws:iam::662924458234:role/lambda_execution_role

package:
  individually: true
  exclude:
    - ./**

functions:
  PostArticle:
    handler: lambda_function.lambda_handler
    package:
      include:
        - PostArticle/**
    module: PostArticle
    layers: arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-pillow:1
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:ap-northeast-1:662924458234:table/hpe_content_buffer/stream/2024-04-08T06:15:36.129

  InsertArticleToDynamoDB:
    handler: lambda_function.lambda_handler
    package:
      include:
        - InsertArticleToDynamoDB/**
    module: InsertArticleToDynamoDB
    timeout: 600
    events:
     - schedule: rate(10 minutes)

plugins:
  - serverless-python-requirements