service: hpefunctions
frameworkVersion: "3"

provider:
  name: aws
  architecture: x86_64
  region: ap-northeast-1
  stage: prod
  runtime: python3.9
  iam:
    role: arn:aws:iam::662924458234:role/lambda_execution_role
  ecr:
    images:
      extract_and_load_to_bq:
        path: ./ExtractAndLoadToBQ

package:
  individually: true
  exclude:
    - ./**

functions:
  PostArticle:
    handler: lambda_function.lambda_handler
    package:
      include:
        - PostArticle/**
    module: PostArticle
    layers: arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-pillow:1
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:ap-northeast-1:662924458234:table/hpe_content_buffer/stream/2024-04-08T06:15:36.129

  InsertArticleToDynamoDB:
    handler: lambda_function.lambda_handler
    package:
      include:
        - InsertArticleToDynamoDB/**
    module: InsertArticleToDynamoDB
    timeout: 600
    events:
     - schedule: rate(10 minutes)

  ExtractAndLoadToBQ:
    image:
      name: extract_and_load_to_bq
    package:
      include:
        - ExtractAndLoadToBQ/**
    module: ExtractAndLoadToBQ
    timeout: 900
    events:
     - schedule: cron(0 16 * * ? *)
    environment:
      DLT_DATA_DIR : /tmp
      DLT_PIPELINE_DIR : /tmp
      DLT_PROJECT_DIR : /tmp






plugins:
  - serverless-python-requirements