service: hpefunctions
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  architecture: x86_64
  region: ap-northeast-1
  stage: prod
  runtime: python3.9
  iam:
    role: arn:aws:iam::662924458234:role/lambda_execution_role
  ecr:
    images:
      extract_and_load_to_bq:
        path: ./ExtractAndLoadToBQ

package:
  individually: true
  exclude:
    - ./**

functions:
  CreateOGImage:
    handler: lambda_function.lambda_handler
    package:
      include:
        - CreateOGImage/**
    module: CreateOGImage
    layers: arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-pillow:1
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:ap-northeast-1:662924458234:table/hpe_content_buffer/stream/2024-04-08T06:15:36.129
  
  PostTweet:
    handler: lambda_function.lambda_handler
    package:
      include:
        - PostTweet/**
    module: PostTweet
    timeout: 600
    events:
     - sns: arn:aws:sns:ap-northeast-1:662924458234:healthy-person-emulator-socialpost
  
  PostBluesky:
    handler: lambda_function.lambda_handler
    package:
      include:
        - PostBluesky/**
    module: PostBluesky
    timeout: 600
    layers:
      - arn:aws:lambda:ap-northeast-1:662924458234:layer:blueskyruntime:1
    events:
     - sns: arn:aws:sns:ap-northeast-1:662924458234:healthy-person-emulator-socialpost
  
  PostActivityPub:
    handler: lambda_function.lambda_handler
    package:
      include:
        - PostActivityPub/**
    module: PostActivityPub
    timeout: 600
    events:
     - sns: arn:aws:sns:ap-northeast-1:662924458234:healthy-person-emulator-socialpost

  InsertArticleToDynamoDB:
    handler: lambda_function.lambda_handler
    package:
      include:
        - InsertArticleToDynamoDB/**
    module: InsertArticleToDynamoDB
    timeout: 600
    events:
     - schedule: rate(10 minutes)

  ExtractAndLoadToBQ:
    image:
      name: extract_and_load_to_bq
    package:
      include:
        - ExtractAndLoadToBQ/**
    module: ExtractAndLoadToBQ
    timeout: 900
    events:
     - schedule: cron(0 16 * * ? *)
    environment:
      DLT_DATA_DIR : /tmp
      DLT_PIPELINE_DIR : /tmp
      DLT_PROJECT_DIR : /tmp
  
  ReportWeeklySummary:
    handler: lambda_function.lambda_handler
    package:
      include:
        - ReportWeeklySummary/**
    module: ReportWeeklySummary
    timeout: 600
    events:
     - schedule: cron(0 12 ? * 1 *)
  
  ReportLegendaryArticle:
    handler: lambda_function.lambda_handler
    package:
      include:
        - ReportLegendaryArticle/**
    module: ReportLegendaryArticle
    timeout: 600
    events:
     - schedule: cron(0 12 ? * * *)

plugins:
  - serverless-python-requirements
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_API_KEY}
    exclude:
      - ExtractAndLoadToBQ